language: node_js
node_js:
- lts/*
stages:
- test
- name: build
  if: branch = master
jobs:
  include:
  - stage: test
    script: yarn test:unit
  - stage: build
    script: yarn build
env:
  global:
    secure: re1O7LZUmHD9H51+KJJmFFvvQl1L/Qc6na9nR463zUGrC/CrkuYVC4xYIQSPiHguuaunzqOAtquKE/sRFf8zIwbQjOAr15TDMbmgDCv9ax+WbflxhhpLZeSGBoc47fXvKHaYJYVrLOcVg7dcFWOp/+JveyAdOF8kKVa1V9YiBg7F9829aXA61bMAJxhX3vrsJWzDQRauRk8pKMQrxNmqH9fk+KvtNGTDJGJV0xnPOjhljCkl1qXVTy8w0RIEBOH5LceOZ+nEOeKCamn4iccg5Eqyps0wyjt2GfevxI8IDjujJ4v+PcLtsAxZaq1ByQeynDxFpRyfHnONJsh+kqy+Vdm7jBIt1fK2DSdVPb3fp8UOdCOizMwNAndOWumd4E66n1iu4T8ji7h8Cu2DZQLsTEJweVOlTbUTqOOsX28rFU5FmJWEM3X3ykurDbaNXxrUry1hYSCSa45okcdfliH3jfiFz8ygKF4NztUeAaj7uYFzzblhxRubGEhAw7k1xE7uNwJ6CGgUv6kCNk4Qp0fLTslR4ZnT26RhCWz1/sIw9tRHsrHlrsCvqnYvqpsOK88TktWPNqj+5SXRA/dGdLN8T5A4MmLgA+5clIqySk3KCMa9XkXEvjKjFGwBbuq/pfXekbvUpcFe4qXsGLYAt5WCqP/yunT6gFBGdJpXBdk07nM=
