language: node_js
node_js:
- lts/*
stages:
- test
- name: build
  if: branch = master
jobs:
  include:
  - stage: test
    script: yarn test:unit
  - stage: build
    script: yarn build
env:
  global:
  - secure: mM5tKFTe3mzY0bS4Oc40prChi6epBiA2AVVjJBI+Uy3p7SQg7IgIeg/VkaoGRLOuQdQMGbXoSJ7reUX1Cm7aqH9UAnH0WZTUhAxhUSdAZJu/GiMKOBn7TRbYVjVJhz+Hrw08BRXlmS8pHhqbyBNu7roLUcbPshzXBGF5zZv1bej1eVDCCn7Ups6Iz0ClA9b2DPLe2ZBkVpIbIg1j6jq+JmZs1hPNNkSwa5VUKU0JSIO2bjcFN5HEeuvc8z2XBau/weJcOB18NV73khMELc9o4XUzMsgSyNK/bqnEpw4v4ol0N/Ew7/C1YBvWlUKn6L9VIaNiULuanI4WtbyuIBI+IHHMsQpbtFxJeG4IX3GYkMlS8rBY3NALpjSSC+zdBvohujGcBt3yL1aTAYowv9Z7qng0Yj3nOqdD/jMANdiZPBi4TOZb8HaWuat/phN82Wb8H9GxUHAX0ARhiVg13W4H7v9R0eRh2WisuxEPX5ufkgO3X0Z0bgf7mBXhoYo5FYvUpC8MoY6wbsjzQsRb0h2hWXc7CVMLcKSfASQbyPiaWUovLdm7DlYJGSoMfIPtQwADimCqD/gjpPqEsp8t9ZAUfYNN+vhBFzrh9jDYrf2OsixaD+I0NEmtbDv5fhodkmTIF1YT/avCLwa61q4+0p9+TuFU4Hb8iPRqVMcP9Q2vcSo=
